### ISSUE TITLE
download_and_build_openblas.py should not use cgt module

### ISSUE THREAD

**Issue by gokceneraslan** [joschu/cgt#19]
Since `download_and_build_openblas.py` is used during the cgt compilation, it shouldn't call any cgt functions. Otherwise, compiling `cgt` for the first time is getting a bit tricky. Considering that it just calls `cgt.utils.warn`, it would be much more convenient to replace it with a simpler `print` call.

**Comment by joschu** [comment]
Good call. Fixed.

**Comment by joschu** [comment]
(actually fixed by 97c0a93)
