### ISSUE TITLE
Test test_par_interp.test_matmuls('native', 'single', 'cpu') fails

### ISSUE THREAD

**Issue by nebw** [joschu/cgt#34]
On my system the test fails with the following error message:

test_par_interp.test_matmuls('native', 'single', 'cpu') ... BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

I think this is because I'm using my own version of OpenBLAS which was compiled with NUM_THREADS=4 (see https://github.com/joschu/cgt/pull/33) instead of USE_THREAD=0. Is there anything I can do to help debug the problem?

**Comment by joschu** [comment]
I actually ran into the same problem myself on a 16-cpu machine, which led to the two commits 297ee1 and ef9c8ca. They check for the number of threads before compiling OpenBLAS.
Could you check to see if that fixes the problem for you?

**Comment by joschu** [comment]
I'm going to close the issue as I think it's fixed now. Please let me know if there's still a problem.
