### ISSUE TITLE
Random number generation and graph simplification

### ISSUE THREAD

**Issue by sbos** [joschu/cgt#54]
It seems that multiple calls to random number generation routines (`cgt.randn` and `cgt.rand`) can be reduced to a single call during graph simplification which is probably a bug. 

The code example is https://gist.github.com/sbos/4cfe3e13510b8b670619. 

Even if this is not a bug, such behaviour is not very obvious.

**Comment by joschu** [comment]
That was a bad bug...should be fixed now

**Comment by sbos** [comment]
Yes, it looks so. Thank you very much John!
