### ISSUE TITLE
Negative reshaping check not enforced sometimes

### ISSUE THREAD

**Issue by dementrock** [joschu/cgt#55]
The following code will crash the native backend (segmentation fault):

```
import cgt
x = cgt.matrix('x', dtype='i8')
y = x * x - x
z = y.reshape((-1,))
cgt.function([x], y[z])([[1]])
```

**Comment by joschu** [comment]
Fixed in f2a6cbe. Now at least it aborts with a semi-informative message

    Assertion failed: (newshape[i] >= 0) && "negative size in reshape not supported" (/Users/joschu/.cgt_cache/077da6c8b3cc27164cce2ac33a2e3875_0.cpp:12)
