### ISSUE TITLE
Support for square root operation on Node

### ISSUE THREAD

**Issue by Sentient07** [joschu/cgt#62]
I was trying out this code for profiling cgt and theano for understanding how better the graph optimisations are done in CGT. 
`x = cgt.scalar(name='x', dtype='float32')
y = cgt.scalar(name='y', dtype='float32')
func = np.sqrt((x**2)*(y/x)*(x**3/y**3) -(x**2)*(y/x)*(x**3/y**3) + (x**2)*(y/x)*(x**3/y**3)) 
`
and then i got this error while compiling the function, 
`AttributeError: 'Node' object has no attribute 'sqrt'
`
Would be glad to have square root support 
Thanks

**Comment by nouiz** [comment]
If you cann cgt.sqrt (or similar) instead of numpy np.sqrt(), does it work?

**Comment by joschu** [comment]
Yes, cgt.sqrt will work.
